IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'FirstName')
ALTER TABLE AspNetUsers ADD [FirstName] [nvarchar](128) NOT NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'LastName')
ALTER TABLE AspNetUsers ADD [LastName] [nvarchar](128) NOT NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'CreatedById')
ALTER TABLE AspNetUsers ADD [CreatedById] [nvarchar](450) NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'CreatedOnUtc')
ALTER TABLE AspNetUsers ADD [CreatedOnUtc] [datetime2](6) NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'UpdatedById')
ALTER TABLE AspNetUsers ADD [UpdatedById] [nvarchar](450) NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'UpdatedOnUtc')
ALTER TABLE AspNetUsers ADD [UpdatedOnUtc] [datetime2](6) NULL
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'Active')
ALTER TABLE AspNetUsers ADD [Active] [bit] NOT NULL DEFAULT(1)
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AspNetUsers' AND COLUMN_NAME = 'Deleted')
ALTER TABLE AspNetUsers ADD [Deleted] [bit] NOT NULL DEFAULT(0)
GO
